"""
PDBQT 格式转换工具

将 SDF/PDB 格式转换为 AutoDock Vina 可用的 PDBQT 格式。
PDBQT 包含原子坐标 + 局部电荷 + AutoDock 原子类型。
"""

import os
import subprocess
import tempfile

from rdkit import Chem

from app.tools.base import BaseTool, ToolResult


class RdkitPdbqtConverter(BaseTool):
    """SDF → PDBQT 格式转换工具

    使用 Meeko（auto-meeko）或 obabel 进行转换。
    PDBQT 文件包含配体原子的坐标 + Gasteiger 电荷 + AutoDock 原子类型。
    """

    name = "rdkit_pdbqt_converter"
    description = "将分子 SDF/PDB 转换为 AutoDock PDBQT 格式"

    def convert_sdf_to_pdbqt(self, sdf_path: str, output_path: str = None) -> ToolResult:
        """将 SDF 文件转换为 PDBQT 格式

        优先使用 Meeko（auto-meeko），失败则回退到 obabel。

        Args:
            sdf_path: 输入 SDF 文件路径
            output_path: 输出 PDBQT 路径（可选）

        Returns:
            ToolResult 包含 PDBQT 文件路径
        """
        if output_path is None:
            fd, output_path = tempfile.mkstemp(suffix=".pdbqt", prefix="ligand_")
            os.close(fd)

        try:
            # 方法 1: Meeko (Python)
            result = self._convert_with_meeko(sdf_path, output_path)
            if result.success:
                return result
        except Exception:
            pass

        try:
            # 方法 2: obabel (命令行)
            result = self._convert_with_obabel(sdf_path, output_path)
            if result.success:
                return result
        except Exception:
            pass

        # 方法 3: 纯 RDKit + 手动写入
        return self._convert_pure_rdkit(sdf_path, output_path)

    def _convert_with_meeko(self, sdf_path: str, output_path: str) -> ToolResult:
        """使用 Meeko 进行转换"""
        from meeko import MoleculePreparation, PDBQTWriterLegacy

        mol = next(Chem.SDMolSupplier(sdf_path, removeHs=False))
        if mol is None:
            raise ValueError("无法从 SDF 读取分子")

        preparator = MoleculePreparation()
        mol_setup = preparator.prepare(mol)
        pdbqt_string, is_ok = PDBQTWriterLegacy.write_string(mol_setup)

        if not is_ok:
            raise ValueError("PDBQT 写入失败")

        with open(output_path, "w") as f:
            f.write(pdbqt_string)

        return ToolResult.success(data={"pdbqt_path": output_path})

    def _convert_with_obabel(self, sdf_path: str, output_path: str) -> ToolResult:
        """使用 OpenBabel 命令行转换"""
        subprocess.run(
            ["obabel", sdf_path, "-O", output_path, "--gen3d"],
            check=True,
            capture_output=True,
            timeout=30,
        )
        return ToolResult.success(data={"pdbqt_path": output_path})

    def _convert_pure_rdkit(self, sdf_path: str, output_path: str) -> ToolResult:
        """纯 RDKit 方法：先转 PDB，再写基础 PDBQT

        这是最后的回退方案，只包含坐标和原子类型，不包含精确的 AutoDock 原子类型。
        """
        mol = Chem.SDMolSupplier(sdf_path, removeHs=True)[0]
        if mol is None:
            raise ValueError("无法从 SDF 读取分子")

        pdb_block = Chem.MolToPDBBlock(mol)
        with open(output_path, "w") as f:
            f.write("REMARK  PDBQT generated by RDKit\n")
            f.write(pdb_block)

        return ToolResult.success(data={"pdbqt_path": output_path, "method": "rdkit_fallback"})

    def convert_mol_to_pdbqt(self, mol: Chem.Mol, output_path: str = None) -> ToolResult:
        """从 RDKit Mol 对象直接转换为 PDBQT

        先保存为临时 SDF 再转换。

        Args:
            mol: RDKit Mol 对象
            output_path: 输出路径

        Returns:
            ToolResult 包含 PDBQT 文件路径
        """
        fd, sdf_path = tempfile.mkstemp(suffix=".sdf")
        os.close(fd)

        writer = Chem.SDWriter(sdf_path)
        writer.write(mol)
        writer.close()

        result = self.convert_sdf_to_pdbqt(sdf_path, output_path)

        # 清理临时文件
        try:
            os.unlink(sdf_path)
        except OSError:
            pass

        return result
